[package]
name = "amfi_net_ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
speedy = "0.8.6"
amfi_core = {path = "../amfi_core" }
thiserror = "1.0.56"
