[package]
name = "tur_net_ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
speedy = "0.8.5"
tur = {path = "../tur"}
thiserror = "1.0.39"